let config = {
  SALT: 10,

  ACCOUNT_TYPE_FREE: "free",
  ACCOUNT_TYPE_PREMIUM: "premium",

  ACCOUNT_SIGNED_VIA_FACEBOOK: "facebook",
  ACCOUNT_SIGNED_VIA_GOOGLE: "google",
  ACCOUNT_SIGNED_VIA_APPLE: "apple",
  ACCOUNT_SIGNED_VIA_EMAIL: "email",

  ACCOUNT_STATUS_BANNED: "banned",
  ACCOUNT_STATUS_ACTIVE: "active",

  UNIT_MILILIT: "ml",
  UNIT_GAM: "g",

  VERIFICATION_STATUS_PENDING: 0,
  VERIFICATION_STATUS_COMPLETED: 1
};

config.ACCOUNT_TYPE = [config.ACCOUNT_TYPE_FREE, config.ACCOUNT_TYPE_PREMIUM];

config.ACCOUNT_SIGNED_VIA = [
  config.ACCOUNT_SIGNED_VIA_APPLE,
  config.ACCOUNT_SIGNED_VIA_GOOGLE,
  config.ACCOUNT_SIGNED_VIA_FACEBOOK,
  config.ACCOUNT_SIGNED_VIA_EMAIL
];

config.ACCOUNT_STATUS = [
  config.ACCOUNT_STATUS_BANNED,
  config.ACCOUNT_STATUS_ACTIVE
];

config.UNIT_TYPE = [config.UNIT_MILILIT, config.UNIT_GAM];

module.exports = config;
